### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Spirit-78** [Notebook-Factory/MRItech_notebooks#1]
I installed Octave following the tutorial at pypi.org and it says to do this, but I can't find the executable's directory anywhere in my C?
![image](https://user-images.githubusercontent.com/48299218/105707369-1e29b800-5f13-11eb-9f0f-9d7bc89ebbd1.png)

This is how my environment paths look
![image](https://user-images.githubusercontent.com/48299218/105707936-fc7d0080-5f13-11eb-8ced-790500cf8486.png)

And the only other octave I found was in D with the Anaconda folder, but those were the kernels not the Octave-5 like in the tutorial.
![image](https://user-images.githubusercontent.com/48299218/105708640-06ebca00-5f15-11eb-96b1-92ab43e3b6de.png)

**Comment by zelenkastiot** [comment]
Hi @Spirit-78 where did you install Octave? Not the octave-kernel package but the language itself?

**Comment by Spirit-78** [comment]
I don't have that installed oops

**Comment by zelenkastiot** [comment]
@Spirit-78 Were you able to fix it?

**Comment by Spirit-78** [comment]
In a way? I downloaded Octave 6.1 and I'm having issues plotting stuff, I keep getting this error locally and on Binder:
![image](https://user-images.githubusercontent.com/48299218/105847090-6f9e7980-5fdd-11eb-8beb-1655f938fbca.png)
Also if I download the 4.1 Octave will it still have issues on Binder? I don't understand how these things work I'm sorry
